/**
 * add customer
 */
export const ADD_CUSTOMER_DATA = "GET_CUSTOMER_DATA";
export const ADD_CUSTOMER_DATA_SUCCESS = "GET_CUSTOMER_DATA_SUCCESS";
export const ADD_CUSTOMER_DATA_FAIL = "GET_CUSTOMER_DATA_FAIL";

/**
 * get customers
 */
export const GET_CUSTOMER_DATA = "GET_CUSTOMER_DATA"
export const GET_CUSTOMER_DATA_SUCCESS = "GET_CUSTOMER_DATA_SUCCESS"
export const GET_CUSTOMER_DATA_FAIL = "GET_CUSTOMER_DATA_FAIL"